---
title: "What is Jacobian Leverage?"
description: |
  An attempt to extend the concept of leverage in regression to non-linear models. 
author:
  - name: Longxiang Wu
    url: https://lunghsiang-wu.github.io/longxiangwu/
date: 2025-09-11
preview: jacobian.jpg
output:
  distill::distill_article:
    self_contained: false
    includes:
      in_header: header.html
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

An attempt to extend the concept of *leverage* in regression to *non-linear models*,
of the form

$$y_i = f_i(\mathbf{\theta}) + \epsilon_i \qquad (i = 1, \ldots, n)$$

where $f_i$ is a known function of the vector of parameters $\mathbf{\theta}$. Formally the Jacobian leverage,
$\hat{j}_{ik}$ is the limit as $b \rightarrow 0$ of

$$\{f_i(\hat{\mathbf{\theta}}) - f_i[\hat{\mathbf{\theta}}(k, b)]\}/b$$

where $\hat{\mathbf{\theta}}$ is the *least squares* estimate of $\mathbf{\theta}$ and $\hat{\mathbf{\theta}}(k, b)$ is the corresponding estimate when $y_k$ is
replaced by $y_k + b$. Collecting the $\hat{j}_{ik}$s in an $n \times n$ matrix $\mathbf{J}$ give

$$\hat{\mathbf{J}} = \hat{\mathbf{V}}(\hat{\mathbf{V}}'\hat{\mathbf{V}} - [\hat{\mathbf{\epsilon}}'][\hat{\mathbf{W}}])^{-1}\hat{\mathbf{V}}'$$

where $\hat{\mathbf{\epsilon}}$ is the $n \times 1$ vector of residuals with elements $\mathbf{\epsilon}_i = y_i - f_i(\hat{\mathbf{\theta}})$ and
$[\hat{\mathbf{\epsilon}}'][\hat{\mathbf{W}}] = \sum_{i=1}^{n} \hat{\mathbf{\epsilon}}_i \hat{\mathbf{W}}_i$: $\mathbf{W}_i$ denotes the *Hessian matrix* of $f_i(\mathbf{\theta})$ and $\hat{\mathbf{V}}$ is the matrix whose
$i$th row is $\partial f_i(\mathbf{\theta})/\partial \mathbf{\theta}'$ evaluated at $\mathbf{\theta} = \hat{\mathbf{\theta}}$. The elements of $\mathbf{J}$ can exhibit *superleverage*.
