---
title: "What is Chi-Squared Test?"
description: |
  A short description of the post.
author:
  - name: Longxiang Wu
    url: https://lunghsiang-wu.github.io/longxiangwu/
date: 2024-05-30
preview: cs.jpg
output:
  distill::distill_article:
    self_contained: false
    includes:
      in_header: header.html
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**chi-squared test (Pearson goodness-of-fit test)** A \*goodness-of-fit test, introduced by Karl \*Pearson in 1900, that is popular because of its simplicity. Let $O$ denote the observed \*frequency of an outcome in a \*sample and let $E$ denote the corresponding \*expected frequency under some \*model. The test statistic is $X^2$, defined by

$$X^2 = \Sigma r^2,$$

where the summation is over all the outcomes whose frequencies are being compared, and $r$, the **Pearson residual**, is defined by

$$r = \frac{O - E}{\sqrt{E}}.$$
It is important to note that the comparison involves frequencies and not proportions.

If there are $m$ observed frequencies, and $p$ \*parameters have been estimated using these frequencies, then, if the model is correct, the observed value of $X^2$ will approximate an observation from a \*chi-squared distribution with $(m - p - 1)$ \*degrees of freedom. In the case of a \*continuous random variable, the frequencies will refer to ranges of values. For other random variables it is usual to combine together neighbouring rare values into a single category, since the chi-squared approximation fails if there are too many small expected frequencies.

As an example, suppose it is hypothesized that a type of sweet pea occurs in shades of white, red, pink, and blue, with proportions $\frac{1}{4}p$, $(\frac{3}{4} - 3p)$, and $2p$, respectively. A random sample of 120 seeds is sown. All germinate with 20 having white flowers, 10 having red flowers, 40 pink, and 50 blue. The question is whether these results are consistent with the hypothesis. In this case the \*maximum likelihood estimate of $p$ is 0.15, so the expected frequencies are 30, 18, 36, and 36. Thus

$$X^2 = \frac{(20-30)^2}{30} + \frac{(10-18)^2}{18} + \frac{(40-36)^2}{36} + \frac{(50-36)^2}{36} = 12.8.$$

There are $4 - 1 - 1 = 2$ degrees of freedom. Since 12.8 is a very large value (compared with the percentage points (Appendix VIII) of a $\chi^2_2$-distribution), the hypothesis can confidently be rejected.

One situation in which the use of the chi-squared test is frequently encountered is as a test for \*independence in a $J \times K$ \*contingency table that cross-classifies the variables $A$ and $B$. Let the observed frequency of data belonging to category $j$ of variable $A$ and to category $k$ of variable $B$ be $f_{jk}$. Write

$$f_{jo} = \sum_{k=1}^{K} f_{jk}, \qquad f_{ok} = \sum_{j=1}^{J} f_{jk}, \qquad f_{oo} = \sum_{j=1}^{J}\sum_{k=1}^{K} f_{jk}.$$

Then, according to the \*null hypothesis of independence, the expected frequency $e_{jk}$ is given by

$$e_{jk} = \frac{f_{jo}f_{ok}}{f_{oo}},$$

and the test statistic $X^2$ is given by

$$X^2 = \sum_{j=1}^{J}\sum_{k=1}^{K} \frac{(f_{jk} - e_{jk})^2}{e_{jk}}.$$

If the null hypothesis of independence is correct, then the distribution of $X^2$ can be approximated by a chi-squared distribution with $(J-1)(K-1)$ degrees of freedom. In the special case where $J = K = 2$ (a two-by-two table), the chi-squared approximation is improved by using the Yates-corrected chi-squared test (*see* TWO-BY-TWO TABLE).

In 1946 \*Cramér suggested that a measure of \*association could be based on the value of $X^2$. This is **Cramér's V**, given by

$$V = \sqrt{\frac{X^2}{Mf_{oo}}},$$

where $M$ is the smaller of $J - 1$ and $K - 1$.


